from groundwork_web.patterns.gw_web_pattern.gw_web_pattern import GwWebPattern
from groundwork_web.patterns.gw_web_db_admin_pattern.gw_web_db_admin_pattern import GwWebDbAdminPattern
from groundwork_web.patterns.gw_web_db_rest_pattern.gw_web_db_rest_pattern import GwWebDbRestPattern
from groundwork_web.patterns.gw_web_doc_pattern.gw_web_doc_pattern import GwWebDocPattern
